version: '3.2'
services:
  php:
    container_name: boost_test
    build:
          context: ./apache-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/var/www/boost-test:z
    ports:
      - '80:80'

